use_frameworks!

target 'NumericPicker_Example' do
  pod 'NumericPicker', :path => '../'

  target 'NumericPicker_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0' # to whatever swift version you're using
    end
  end
end
