platform :ios, '10.3'
use_frameworks!

target 'NumericPicker_Example' do
  pod 'NumericPicker', :path => '../'

  target 'NumericPicker_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '4.0' # to whatever swift version you're using
    end
  end
end
