use_frameworks!

target 'NumericPicker_Example' do
  pod 'NumericPicker', :path => '../'

  target 'NumericPicker_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
